const VERSIONS_URL = 'http://realwargame.ru/download/version.json';

const IPC_CHANNELS = {
  CHANNEL_GET_REMOTE_DATA: 'CHANNEL_GET_REMOTE_DATA',
  CHANNEL_REPLY_GET_REMOTE_DATA: 'CHANNEL_REPLY_GET_REMOTE_DATA',
  CHANNEL_GET_REGISTRY_DATA: 'CHANNEL_GET_REGISTRY_DATA',
  CHANNEL_REPLY_GET_REGISTRY_DATA: 'CHANNEL_REPLY_GET_REGISTRY_DATA',
  CHANNEL_RUN_GAME_EXE: 'CHANNEL_RUN_GAME_EXE',
  CHANNEL_REPLY_RUN_GAME_EXE: 'CHANNEL_REPLY_RUN_GAME_EXE',
  CHANNEL_RUN_GAME_UPDATE_EXE: 'CHANNEL_RUN_GAME_UPDATE_EXE',
  CHANNEL_REPLY_RUN_GAME_UPDATE_EXE: 'CHANNEL_REPLY_RUN_GAME_UPDATE_EXE',
  CHANNEL_RUN_EDITOR_EXE: 'CHANNEL_RUN_EDITOR_EXE',
  CHANNEL_REPLY_RUN_EDITOR_EXE: 'CHANNEL_REPLY_RUN_EDITOR_EXE',
  CHANNEL_DOWNLOAD_UPDATE: 'CHANNEL_DOWNLOAD_UPDATE',
  CHANNEL_REPLY_DOWNLOAD_UPDATE: 'CHANNEL_REPLY_DOWNLOAD_UPDATE',
}

module.exports = {
  VERSIONS_URL,
  IPC_CHANNELS,
}